### ISSUE TITLE
Invalid Cache Directory for Task

### ISSUE THREAD

**Issue by rickihastings** [davidgarciab/nx-gcp-cache#1]
Hi,

It seems that a recent change in Nx is causing remote cache entries to often fail, it's pretty difficult to recreate but in our monorepo we're getting this error intermittently.

```
 >  NX   Invalid Cache Directory for Task "**"

   The local cache artifact in "/home/runner/work/**/node_modules/.cache/nx/9592402972363641654" was not been generated on this machine.
   As a result, the cache's content integrity cannot be confirmed, which may make cache restoration potentially unsafe.
   If your machine ID has changed since the artifact was cached, run "nx reset" to fix this issue.
   Read about the error and how to address it here: https://nx.dev/recipes/troubleshooting/unknown-local-cache
```

Looking at this issue https://github.com/nrwl/nx/issues/19159 and this https://github.com/bojanbass/nx-aws/pull/376 - it looks like remote runners should be excluding the `source` file from the cache.

Would you agree this is correct? I'm happy to put a PR in for this btw, I just wanted to raise an issue first to clarify this behaviour is correct.

It appears setting `REJECT_UNKNOWN_LOCAL_CACHE=0` fixes this as a workaround but is discouraged by Nx.

**Comment by davidgarciab** [comment]
HI @rickihastings, looking to the issues mentioned you're totally right, `source` file should be excluded from the cache.
Please, feel free to create a PR to fix it and I'll expedite the the package generation.

Thanks!
